# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/GaussianRegularization',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/GaussianRegularization',
                'lib_path': 'GaussianRegularization'},
  'syms': {'GaussianRegularization.core': {'GaussianRegularization.core.foo': ('core.html#foo', 'GaussianRegularization/core.py')}}}